### PR TITLE
Fix for #46.

### PR DESCRIPTION
**Pull request by reistiago**
Code compiles but probably doesn't follow the ideas desired by the original code refactor that broke the compilation when merged to master

### CODE REVIEW

**Comment by vietj** [comment]
it's not clear wether it's a full fix or not

**Comment by reistiago** [comment]
@vietj  can you please elaborate? Code compiles and tests pass.

**Comment by reistiago** [comment]
@vietj Fixed/Updated xhr paths and tested locally generating a project. 

Too me it looks functional, please elaborate if something else is missing.

**Comment by vietj** [comment]
thanks @reistiago

**Comment by reistiago** [comment]
Happy to help @vietj. 

Please close https://github.com/vert-x3/vertx-starter/issues/46 when you have time

**Pull request merged**
