### PR TITLE
Generate start method with Promise argument if version is 3.8.x

### LINKED ISSUE #110: Verticle start method should take a Promise argument instead of Future
The generated verticle start method should take a `Promise` arg on Vert.x 3.8.x and 4.x projects.

### PR DESCRIPTION
**Pull request by okou19900722**
fixed #110

### CODE REVIEW

**Comment by tsegismont** [comment]
@okou19900722 thanks for sending this PR. I would prefer to keep the logic in the template. I've just merged #109 that does the job for 4.x. Would you mind to update the templates so that 3.8.x also uses `Promise`?

**Comment by okou19900722** [comment]
This was the case before, but I can't find a way to compare two strings. So I moved the logic to the java code. Do you have any suggestions to compare the two version numbers?

**Comment by tsegismont** [comment]
@okou19900722 I believe it's fine to just verify the version string starts with `3.8`

**Comment by okou19900722** [comment]
all right, work in process

**Comment by okou19900722** [comment]
it's done, but it has a issues if a new version called 3.9

**Comment by tsegismont** [comment]
@okou19900722 thanks for the fast turnaround. 

No worries, there is no 3.9 scheduled. 3.8 should be the last 3.x version. If that changes, we'll revisit the code. In the worst case, it will not break but simply generate deprecated code.

**Pull request merged**
