### PR TITLE
Fix Gradle versions + version upgrades

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by tsegismont** [comment]
Thank you @jponge !

**Comment by tsegismont** [comment]
Wait. Actually this should be removed https://github.com/vert-x3/vertx-starter/blob/ad4bd8092b32fa0ea478c152710f8ba3f8459fca/src/main/resources/templates/build.gradle.ftl#L42

**Comment by jponge** [comment]
Ah yes

**Comment by jponge** [comment]
Here you go @tsegismont

**Comment by tsegismont** [comment]
Thanks @jponge

**Pull request merged**
