### PR TITLE
Provide in the UI the generation commands with a copy button

### LINKED ISSUE #87: Provide in the UI a curl command with a copy button
Firstly, great work!
This ticket asks if we can have `<pre>` style element in the UI with a parameterised curl command. Next to it, there would be a button (with a suitable icon) to copy the contents of the element, so that it can be pasted into a suitable terminal that would initiate the download of the project. Thanks again, Fuzz.

### PR DESCRIPTION
**Pull request by danielpetisme**
Fixes #87 

Just as Github/Gitlab provides the `git clone` commands to ease developer's job, this PR aims to provide the CLI commands to generate a Vertx project via the starter.

### CODE REVIEW

**Comment by danielpetisme** [comment]
This is a UI proposal. I used a button group to split the generation button in 2 parts. On the left, it keeps its behavior, if clicked the project is generated and downloaded. On the right, I use the font awesome terminal icon to trigger a dropdown. You can then see the curl/HTTPie commands to generate the project + buttons to copy the command into the clipboard.

So far, it's a working prototype (the commands are not correct yet)
Capture d’écran 2019-03-28 à 23 37 14

Capture d’écran 2019-03-28 à 23 37 19

WDYT?
At some point, we were discussing about Windows command? What did you have in mind? Since the hotkeys are already OS dependent, i propose to use the same path for the CLI (ie. if Windows's detected the content of the dropdown would be different).

**Comment by dazraf** [comment]
I love it!

**Comment by vietj** [comment]
very nice

**Comment by tsegismont** [comment]
Awesome @danielpetisme !

Yes, from a quick look at the project stats, Windows users are far from a minority.

If you can change the content of the panel depending on the user OS, then having curl/httpie for *nix and Powershell for Windows would be great.

Otherwise, I believe you could stick to curl/powershell (and that would be great already).

Also, perhaps the the terminal button color should be different when not focused/clicked so that you can catch the user eyes.

Looking forward this to land in master!

**Comment by danielpetisme** [comment]
Choosing a style for the Terminal button isn't obvious. To be consistent with the Vert.x website look'n'feel I used `btn-default` which make the button blank (not my favorite...).
WDYT.
Capture d’écran 2019-04-06 à 20 27 13
I've tested the `curl` and `httpie` command generation, i'll test powershell soon. Do you see another way to test it more automatically?

**Comment by tsegismont** [comment]
I'll defer the design question to the artist of the gang, namely @jponge :smile: 

It is fine to start without automated testing (we don't have tests for the rest UI either). We'll revisit later if it proves to be a problem.

**Comment by jponge** [comment]
The button thing is ok.

Now as far as design is concerned, I'd rather have labels right-aligned rather than left-aligned, as in:

```
hello: [            ]
  foo: [            ]
 plop: [            ]
    a: [            ]
```

**Comment by danielpetisme** [comment]
@jponge you mean the label for the form inputs ? (groupId, build, etc.) ? If it's that, you're right, but I propose to fix it in a dedicated PR (with a global UI/UX review?)

**Comment by jponge** [comment]
Yes

**Comment by pmlopes** [comment]
does it make sense to have 2 items? curl and httpie? why not just the url, then you can use any tool

**Comment by danielpetisme** [comment]
Only the url is not CLI compliant. You have still to type/adapt the url to
actually generate the project.

Maybe you're right and 2 options is confusing. I'm not used to httpie and
curl is like a standard, so we can keep only curl *NIX environnement and
PowerShell for Windows.

But IMHO, it must be a copy/paste command like in github/lab.

WDYT?

Le lun. 8 avr. 2019 à 17:36, Paulo Lopes <notifications@github.com> a
écrit :

**Comment by pmlopes** [comment]
I agree with the copy paste url, my only concern was that it would be confusing to have 2 entries, and indeed perhaps:

1. curl
2. powershell

would make more sense as it covers the majority of users, *nix / windows.

**Comment by jponge** [comment]
httpie is more a tool for developers, while curl is a general-purpose HTTP cli tool.

**Comment by danielpetisme** [comment]
I finished the Powershell Command generation. There is a [PowerShell Core Docker image](https://hub.docker.com/_/microsoft-powershell) if you want to have a try.

Capture d’écran 2019-04-09 à 14 19 55

Regarding the curl and/or httpie... The code is here, it works for both tools... My 2cts, would be propose the 2 commands and remove one if we have complains.

Folks, you have more experience on that, tell me what to do.

@tsegismont can you do a first review 🙏

**Comment by tsegismont** [comment]
+1 to address separate UI concerns in another PR

Will take a look at the PR asap

**Comment by tsegismont** [comment]
I've checked out the PR branch on my laptop to give this a try.

This command was generated for `curl`: 

```
curl http://localhost:8080/starter.zip?groupId=com.example&artifactId=starter&vertxVersion=3.7.0&language=java&jdkVersion=1.8&buildTool=maven --output starter.zip
```

And here's the output:

```
[tsegismont@stetson vertx-starter]$ curl http://localhost:8080/starter.zip?groupId=com.example&artifactId=starter&vertxVersion=3.7.0&language=java&jdkVersion=1.8&buildTool=maven --output starter.zip
[1] 17538
[2] 17539
[3] 17540
[4] 17541
[5] 17542
bash: --output: commande inconnue...
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
[2]   Fini                    artifactId=starter
[3]   Fini                    vertxVersion=3.7.0
[4]-  Fini                    language=java
[1]   Termine 23              curl http://localhost:8080/starter.zip?groupId=com.example
[2]   Fini                    artifactId=starter
[3]   Fini                    vertxVersion=3.7.0
[4]-  Fini                    language=java
[5]+  Fini                    jdkVersion=1.8
```

You could either use quotes or `-G` together with `-d` for parameters.

Also, it would be nice to have a tooltip telling you the command was copied to clipboard, fading away after a couple of seconds.

**Comment by danielpetisme** [comment]
Ok I reproduced your issue by using Bash rather my usual Zsh. I've updated the command to use the curl options, IMHO is the more reliable way to provide a portable command. Could you please try:
`curl -G http://localhost:8080/starter.zip -d "groupId=com.example&artifactId=starter&vertxVersion=3.7.0&language=java&jdkVersion=1.8&buildTool=maven" --output starter.zip`

Regarding the tooltip, I was surprised Github doesn't show something equivalent when you hit the repo url copy button... Anyway, I've added it. Before the dropdown was closed when you have click the copy button, now the dropdown closes only if you click outside. When you click on the copy button the tooltip appears.

Capture d’écran 2019-04-12 à 11 19 26

**Comment by tsegismont** [comment]
Awesome!

The new command works in bash, but if we are to go down the `curl` options route, let's go the whole nine yards:

```
curl -G http://localhost:8080/starter.zip -d "groupId=com.example" -d "artifactId=starter" -d "vertxVersion=3.7.0" -d "language=java" -d "jdkVersion=1.8" -d "buildTool=maven" --output starter.zip
```

**Comment by danielpetisme** [comment]
🎉 "idiomatic" curl!
`curl -G http://localhost:8080/starter.zip -d "groupId=com.example" -d "artifactId=starter" -d "vertxVersion=3.7.0" -d "vertxDependencies=vertx-web,vertx-web-client" -d "language=java" -d "jdkVersion=1.8" -d "buildTool=maven" --output starter.zip`

From my side, it's feature complete.

**Comment by tsegismont** [comment]
@danielpetisme looks good to me. Cherry on top would be to hide the panel and block the icon when the form is invalid.

**Comment by danielpetisme** [comment]
If the form is invalid, the generate button isn't available? The CLI generation is made when you click on the terminal icon, it doesn't listen to all the form changes. That means, if the form is not valid the Generate button is not available thus the copy button neither.

**Comment by tsegismont** [comment]
@danielpetisme yes, the [generate button is disabled](https://github.com/vert-x3/vertx-starter/blob/master/src/main/resources/webroot/index.html#L296) when the form is invalid. It's not a blocker for me but I wonder if blocking the popup is not just a matter of adding an attribute.

**Comment by danielpetisme** [comment]
Hum... Not sure to get what you call the popup. It's the dropdown panel
which appears when you click on the terminal icon or something else ?

Le lun. 15 avr. 2019 à 21:55, Thomas Segismont <notifications@github.com> a
écrit :

**Comment by tsegismont** [comment]
Le lun. 15 avr. 2019 à 22:20, Daniel PETISME <notifications@github.com> a
écrit :

> Hum... Not sure to get what you call the popup. It's the dropdown panel
> which appears when you click on the terminal icon or something else ?
>

Yes, the dropdown panel :)

**Comment by danielpetisme** [comment]
https://stackoverflow.com/questions/15697968/how-to-disable-bootstraps-button-dropdown

Looks easy, I'll try tomorrow. Stay tuned

Le lun. 15 avr. 2019 à 22:21, Thomas Segismont <notifications@github.com> a
écrit :

**Comment by danielpetisme** [comment]
@tsegismont 🍒 
Capture d’écran 2019-04-16 à 11 09 17

I squashed the commits too.

**Comment by tsegismont** [comment]
@danielpetisme awesome, thanks!

**Comment by dazraf** [comment]
Great work, thank you!

**Comment by jponge** [comment]
Awesome 👏

**Pull request merged**
