### PR TITLE
Gradlew upgrade to 7

### PR DESCRIPTION
**Pull request by tsegismont**

### CODE REVIEW

**Comment by tsegismont** [comment]
Gradle 7 cannot build Kotlin projects without workarounds so far https://youtrack.jetbrains.com/issue/KT-46165

**Comment by wowselim** [comment]
With gradle 7, [the shadow plugin can also be upgraded to version 7](https://github.com/johnrengelman/shadow/releases/tag/7.0.0). This would take care of https://github.com/vert-x3/vertx-starter/pull/164 as well. WDYT @tsegismont?

**Comment by tsegismont** [comment]
@wowselim hi! Yes, I have the shadow plugin update in mind so that we can finally merge #164.

Until the issues with Gradle 7 are sorted out, I prefer to stick to the current version.

**Comment by wowselim** [comment]
@tsegismont that would be great. I was able to build a project with this config:

- Kotlin v1.5.0
- Shadow v7.0.0
- Gradle v7.0

You can see the build output [here](https://github.com/wowselim/vertx-kotlin-gradle7/runs/2491360885) and the `build.gradle` file [here](https://github.com/wowselim/vertx-kotlin-gradle7/blob/master/build.gradle.kts).

The project was generated from the starter and all I changed was those three version bumps.

**Pull request merged**
