### PR TITLE
Stack module definitions exclusions

### LINKED ISSUE #85: Stack module definitions exclusions
Update stack module definitions file so that some modules can only be selected with specific versions of the project.

For example, Vert.x Web GraphQL should be available starting with 3.7, not before.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #85

Modified the stack definition format to include a list of versions with excluded modules.

On the client side, dependency excluded in a specific version is removed when this version is selected.

Split the verticle code into:

- project validation
- project generation
- metadata definition

Also:

- Modified UI to use radio buttons for Vert.x version, build tool and
language
- Use metadata to get supported JDK versions
- Vert.x core dependency now added in build file only when no other dependency is selected
- Expanded test coverage (all params tested in validation, much more combinations in generation)

### CODE REVIEW

**Comment by tsegismont** [comment]
@jponge @danielpetisme this is a draft PR. It misses:

- client side code update (change dependencies if modules is not available in selected version)
- tests for project validator (server side)

Would appreciate any feedback you have so far.

**Comment by tsegismont** [comment]
@jponge @danielpetisme I'm done with this PR. It's a big one sorry, when you review, try to focus on the #85 goal that is to prevent some dependencies to be added with specific versions (e.g. no GraphQL in 3.6.3).

When this is merged, I'll release a new version of the starter so that we can get the awesome #87  from @danielpetisme online

**Comment by jponge** [comment]
GraphQL is only proposed in 3.7 ✅ 

I also did a few runs 👍 

Looks good to me!

**Comment by tsegismont** [comment]
@jponge thank you. It should be proposed in `4.0.0-SNAPSHOT` as well, isn't it?

**Comment by jponge** [comment]
Yes it does.

**Pull request merged**
