### PR TITLE
Few fixes to Gradle build file

### PR DESCRIPTION
**Pull request by spodin**

### CODE REVIEW

**Comment by danielpetisme** [comment]
Thanks for your PR.

What do you think of storing dependencies versions in a dedicated `gradle.properties` file rather than ```
ext {
  vertxVersion = '{{version}}'
}
```
I'm not a gradle expert but I always tempted to split concerns. A Build file to list the plugin/dependencies and a property file to store the version.

Second point, I would recommend to use underscore `_` as separator rather than came casing.

**Comment by danielpetisme** [comment]
As ask via #33 the project formatting required to be aligned with Vert.x standards #38 fix this issue. Please consider to fetch the updates before moving forward on your PR.
Thanks.

**Comment by spodin** [comment]
I think, that dependency is single concern and it isn't a good idea to split it's declaration among different files.

`gradle.properties` is right place to define build environment variables (e.g.: `org.gradle.*`, `systemProp.*` or credentials for user home files).

### `def` vs `ext` block

In Vert.x Gradle Starter project [versions are defined in build file using `def` keyword](https://github.com/vert-x3/vertx-gradle-starter/blob/master/build.gradle#L14), and here I'm agree with:

> Keyword `def` comes from Groovy and means that variable has [local](https://stackoverflow.com/questions/184002/groovy-whats-the-purpose-of-def-in-def-x-0) scope.
> 
> Using `ext.outDir` means that you add property `outDir` to [ExtraPropertiesExtension](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.ExtraPropertiesExtension.html), think of it like project has a map of properties with name ext, and you put your property in this map for later access.

source: https://stackoverflow.com/questions/37186108/gradle-def-vs-ext

Summarizing all above: `ext` block wins for dependency versions.

### Underscore as separator

All Gradle native properties like Java plugin's properties (`sourceCompatibility`, `mainClassName`) are defined using camel case, so using underscores will break build file style, isn't it?

**Comment by danielpetisme** [comment]
Interesting point. I propose to move on with your proposal and wait for feedback.

**Pull request merged**
