### PR TITLE
Default JDK selection

### LINKED ISSUE #120: Default JDK selection to latest OpenJDK
#### Describe the feature

The actual default selection for the JDK is 1.8. Who starts a new project probably wants to start with the latest version of the JDK (unless particular situations), so I think we should default to the latest OpenJDK, so OpenJDK 13

#### Contribution

I can take care of it, just point me the chords i need to touch :smile:

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fix #120
Also fixed wrong docker command in README

Screenshot_2020-04-03 Vert x Starter - Create new Eclipse Vert x applications

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
For the `pom.xml` this should do it, while for the `build.gradle` I can't find anything about the build target (but i don't know if it's needed in gradle).

**Comment by jponge** [comment]
> For the `pom.xml` [this](https://github.com/vert-x3/vertx-starter/pull/121/commits/95fbef166723211d3cddd31c3ef181bf1d542d46) should do it, while for the `build.gradle` I can't find anything about the build target (but i don't know if it's needed in gradle).

https://docs.gradle.org/current/userguide/building_java_projects.html

```groovy
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
```

**Comment by tsegismont** [comment]
@jponge we have this
https://github.com/vert-x3/vertx-starter/blob/master/src/main/resources/templates/build.gradle.ftl#L41-L43

**Comment by jponge** [comment]
You can double with targetCompatibility

**Comment by jponge** [comment]
Well it should be in a `java { }` block

**Comment by tsegismont** [comment]
@jponge would you mind to send a PR?

**Comment by jponge** [comment]
See https://github.com/vert-x3/vertx-starter/pull/122

**Pull request merged**
